<a href="https://colab.research.google.com/github/bigyandulal2/datascience/blob/main/outlier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv("Outlier-Practice.csv")

In [4]:
df.describe().round(1)

       EmployeeID    Salary  Experience
count        20.0      20.0        20.0
mean         10.5   52025.0         2.6
std           5.9   27170.3         2.0
min           1.0   12000.0         0.0
25%           5.8   41750.0         1.8
50%          10.5   46500.0         2.0
75%          15.2   51250.0         3.0
max          20.0  150000.0        10.0

In [3]:
df.head()

   EmployeeID Department  Salary  Experience
0           1         IT   52000           3
1           2         IT   55000           4
2           3         IT   48000           2
3           4         IT   51000           3
4           5         IT   53000           4

In [5]:
df["Salary"].unique()

array([ 52000,  55000,  48000,  51000,  53000,  95000,  49000,  45000,
        47000,  46000,  44000,  43000,  40000,  41000,  39000,  42000,
        40500, 150000,  12000])

In [6]:
#use interquartile range (IQR method )
Q1=df["Salary"].quantile(0.25);
Q3=df["Salary"].quantile(0.75);
IQR=Q3-Q1

In [8]:
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
#find outliers
outliers=df[(df["Salary"] < lower_bound) |(df["Salary"] > upper_bound) ]

In [9]:
print(outliers)

    EmployeeID Department  Salary  Experience
5            6         IT   95000           2
18          19      Sales  150000          10
19          20      Sales   12000           0